"""Initial migration

Revision ID: 630b61e203b1
Revises: 
Create Date: 2024-06-14 15:56:10.412106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630b61e203b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_recepcion', sa.String(), nullable=True),
    sa.Column('campo_con_error', sa.String(), nullable=True),
    sa.Column('debe_decir_otros_campos', sa.String(), nullable=True),
    sa.Column('falta_sacar_deducible', sa.String(), nullable=True),
    sa.Column('saco_deducible_erroneo', sa.String(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=True),
    sa.Column('razon', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_entry')
    # ### end Alembic commands ###
