"""create OtherFields class and table

Revision ID: bff8e2a16ffd
Revises: acfd6171dc52
Create Date: 2024-07-05 16:05:03.477203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff8e2a16ffd'
down_revision = 'acfd6171dc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_qa_monto_deducible',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio_recepcion', sa.String(), nullable=True),
    sa.Column('mes', sa.String(), nullable=True),
    sa.Column('debe_decir_otros_campos', sa.String(), nullable=True),
    sa.Column('falta_sacar_deducible', sa.String(), nullable=True),
    sa.Column('saco_deducible_erroneo', sa.String(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=True),
    sa.Column('razon', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.Column('fecha_rev', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_qa_otros_campos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio_recepcion', sa.String(), nullable=True),
    sa.Column('mes', sa.String(), nullable=True),
    sa.Column('campo_con_error', sa.String(), nullable=True),
    sa.Column('debe_decir_otros_campos', sa.String(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=True),
    sa.Column('razon', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.Column('fecha_rev', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('revision_qa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_qa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folio_recepcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('campo_con_error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('debe_decir_otros_campos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('falta_sacar_deducible', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('saco_deducible_erroneo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responsable', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('razon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comentarios', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='revision_qa_pkey')
    )
    op.drop_table('revision_qa_otros_campos')
    op.drop_table('revision_qa_monto_deducible')
    # ### end Alembic commands ###
