"""name change

Revision ID: ea79df2773fd
Revises: 630b61e203b1
Create Date: 2024-06-14 16:02:24.691384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea79df2773fd'
down_revision = '630b61e203b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_recepcion', sa.String(), nullable=True),
    sa.Column('campo_con_error', sa.String(), nullable=True),
    sa.Column('debe_decir_otros_campos', sa.String(), nullable=True),
    sa.Column('falta_sacar_deducible', sa.String(), nullable=True),
    sa.Column('saco_deducible_erroneo', sa.String(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=True),
    sa.Column('razon', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folio_recepcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('campo_con_error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('debe_decir_otros_campos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('falta_sacar_deducible', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('saco_deducible_erroneo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responsable', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('razon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comentarios', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origen', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='data_entry_pkey')
    )
    op.drop_table('revision_qa')
    # ### end Alembic commands ###
